//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompositeApplicationFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompositeApplicationFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}, {1}, {2}, X={3} ähnelt.
        /// </summary>
        internal static string DropInfo_DebugInfo {
            get {
                return ResourceManager.GetString("DropInfo_DebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot get the templated child of a null object ähnelt.
        /// </summary>
        internal static string FrameworkElementHelper_GetTemplateChild_Cannot_get_the_templated_child_of_a_null_object {
            get {
                return ResourceManager.GetString("FrameworkElementHelper_GetTemplateChild_Cannot_get_the_templated_child_of_a_null_" +
                        "object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die objToHold cannot be type of WeakReference ähnelt.
        /// </summary>
        internal static string ObjectDependencyManager_AddObjectDependency_objToHold_cannot_be_type_of_WeakReference {
            get {
                return ResourceManager.GetString("ObjectDependencyManager_AddObjectDependency_objToHold_cannot_be_type_of_WeakRefer" +
                        "ence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The objToHold cannot be null ähnelt.
        /// </summary>
        internal static string ObjectDependencyManager_AddObjectDependency_The_objToHold_cannot_be_null {
            get {
                return ResourceManager.GetString("ObjectDependencyManager_AddObjectDependency_The_objToHold_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string ThemedWindow_Tooltip_Close {
            get {
                return ResourceManager.GetString("ThemedWindow_Tooltip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximize ähnelt.
        /// </summary>
        internal static string ThemedWindow_Tooltip_Maximize {
            get {
                return ResourceManager.GetString("ThemedWindow_Tooltip_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize ähnelt.
        /// </summary>
        internal static string ThemedWindow_Tooltip_Minimize {
            get {
                return ResourceManager.GetString("ThemedWindow_Tooltip_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore ähnelt.
        /// </summary>
        internal static string ThemedWindow_Tooltip_Restore {
            get {
                return ResourceManager.GetString("ThemedWindow_Tooltip_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string ViewHost_Cancel {
            get {
                return ResourceManager.GetString("ViewHost_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        internal static string ViewHost_Confirm {
            get {
                return ResourceManager.GetString("ViewHost_Confirm", resourceCulture);
            }
        }
    }
}
